In [15]:
import pandas as pd
import numpy as np
import random

In [74]:
data = pd.read_csv("../data/analysis_unsamplingdata_review8.csv")
data

,장소,가게,가격,가계,가구,가기,가능,가능성,가대,가량,...,흥분,흥정,흥행,희귀,희망,희생,흰색,히터,힐링,힘
0,남이섬,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,남이섬,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,남이섬,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,남이섬,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,남이섬,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1667,강릉항요트마리나,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1668,강릉항요트마리나,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1669,강릉항요트마리나,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1670,강릉항요트마리나,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1671,강릉항요트마리나,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
place_list = data.장소.unique().tolist()
place_list

['남이섬',
 '강원도립화목원',
 '정동진해변',
 '쏠비치양양오션플레이',
 '설악산국립공원',
 '경포대',
 '설악워터피아',
 '경포해변',
 '제이드가든',
 '춘천시',
 '등대전망대',
 '낙산사',
 '하슬라아트월드·피노키오미술관',
 '대관령양떼목장',
 '주문진해변',
 '속초해변',
 '바다열차',
 '아바이마을',
 '오색탄산온천',
 '강문해변',
 '오죽헌',
 '모래시계공원',
 '비발디파크오션월드',
 '하이원리조트',
 '하조대',
 '테디베어팜',
 '망상해변',
 '아리힐스-스카이워크',
 '묵호항',
 '원조초당순두부',
 '신흥사',
 '정동진시간박물관',
 '통일전망대',
 '선교장',
 '홍천온천원탕',
 '테디베어박물관',
 '뮤지엄산',
 '환선굴',
 '엘리시안강촌스키리조트',
 '알펜시아스키장',
 '정동진해돋이공원',
 '화진포해변',
 '해양레일바이크',
 '춘천명동닭갈비골목',
 '대포항',
 '참소리축음기·에디슨과학박물관',
 '엑스포타워',
 '김유정문학촌',
 '삼팔선',
 '오대산국립공원',
 '청초호',
 '애니메이션박물관',
 '촛대바위',
 '춘천중앙시장',
 '설악케이블카',
 '대명비발디파크스키월드',
 '장호항',
 '용평리조트',
 '월정사',
 '레일바이크',
 '낙산해변',
 '사천해변',
 '권금성',
 '정동진조각공원',
 '경포호',
 '소양호',
 '오크밸리스키리조트',
 '영랑호',
 '국립미천골자연휴양림',
 '두타산자연휴양림',
 '화암동굴',
 'DMZ박물관',
 '울산암각화박물관',
 '운암정베이커리카페',
 '평창휘닉스파크스키장',
 '천곡황금박쥐동굴',
 '국립춘천박물관',
 '척산족욕공원',
 '소양강처녀상',
 '금강굴',
 '아라나비체험',
 '허브나라농원',
 '아라리촌',
 '웰리힐리파크',
 '치악산국립공원',
 '대관령박물관',
 '대관령자연휴양림',
 '추암해변',
 '무릉계곡',
 '백담사',
 '강원드라마갤러리',
 '공지천',
 '외옹치항',
 '비룡폭포',
 '죽서루',
 '영월한반도지형',
 '장릉',
 '막국수체험박물관',
 '태백산국립공원',
 '강릉단오문화관',
 '박경리문학공원',
 '오션700',
 '천당폭포',
 '대승폭포',
 '횡성풍수원성당',
 '한국자생식물원',
 '파슈파티나트힌두사원',
 '중도관광리조트',
 '대청봉',
 '춘천미술관',
 '(주)브라운5번가',
 '만경대',
 '속초시립박물관',
 '용평피크아일랜드',
 '대금굴',
 '화진포해양박물관',
 '방태산자연휴양림',
 '강촌유원지',
 '천불동계곡',
 '석봉도자기미술관',
 '흥정계곡',
 '동강사진박물관',
 '얼라이브하트',
 '설악해맞이공원',
 '화진포',
 '블루캐년',
 '효석문화마을',
 '정선레일바이크',
 '한솔오크밸리스키장',
 '오투리조트스키장',
 '상원사',
 '삼화사',
 '을지전망대',
 '양구선사박물관',
 '황지연못',
 '태백석탄박물관',
 '범바위',
 '철의삼각전적관',
 '수타사',
 '구곡폭포',
 '청동동상',
 '구룡사',
 '서울종가김치체험관',
 '조선민화박물관',
 '홍천생명건강과학관',
 '학무정',
 '청평사',
 '청령포',
 '금당계곡',
 '양구통일관',
 '동강어라연',
 '두타연',
 '안목해변카페거리',
 '휘닉스스노우파크',
 '안목해변',
 '알파카월드',
 '울산바위',
 '대관령삼양목장',
 '대관령하늘목장',
 '춘천명동거리',
 '봉포해변',
 '코리아인터내셔널스키스쿨',
 '주문진항',
 '원주소금산출렁다리',
 '소양강스카이워크',
 '속초중앙시장',
 '초당동순두부마을',
 '원대리자작나무숲',
 '강릉중앙시장',
 '에티오피아한국전참전기념관',
 '천진해변',
 '별마로천문대',
 '한지테마파크',
 '평창올림픽시장',
 '해신당공원',
 '허균허난설헌기념관',
 '월드온천',
 '통일공원',
 '간현관광지',
 '이효석문학관',
 '하늬라벤더팜',
 '노동당사',
 '얼음나라화천산천어축제',
 '고석정',
 '사천진해변',
 '송지호해변',
 '정선화암굴',
 '고씨굴',
 '커피커퍼',
 '정선아리랑시장',
 '평화의소녀상',
 '휴휴암',
 '영금정',
 '비선대',
 '동명항',
 '아바이마을갯배',
 '낙산사의상대',
 '삼탄아트마인',
 '매봉산풍력발전단지',
 '남애항',
 '검룡소',
 '국립산악박물관',
 '설악씨네라마',
 '제이스키',
 '대명비발디파크볼링장',
 'CGV원주',
 'CGV강릉',
 '원주레일파크',
 '강릉항요트마리나']

In [ ]:
data.columns

In [52]:
user = pd.DataFrame(np.zeros(shape=(1,4132), dtype = np.int8))
user2 = pd.DataFrame(np.zeros(shape=(1,4132), dtype = np.int8))

In [61]:
indexs1 = random.sample(range(0,4132),10)
indexs2 = random.sample(range(0,4132),10)

In [62]:
indexs1,indexs2

([4130, 2153, 2314, 1189, 1046, 36, 3052, 1949, 1426, 3332],
 [645, 3660, 2707, 3729, 1623, 2105, 3204, 1681, 3922, 1368])

In [69]:
user.at[:,indexs] = 1
user2.at[:,indexs2] = 1

In [75]:
user_list = pd.concat([user,user2])
user_list.columns = data.columns

In [76]:
user_list

,장소,가게,가격,가계,가구,가기,가능,가능성,가대,가량,...,흥분,흥정,흥행,희귀,희망,희생,흰색,히터,힐링,힘
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
user_list.to_csv("../data/example_user1.csv", index = False)

In [83]:
place_list[156]
place_list[161]

'코리아인터내셔널스키스쿨'

In [87]:
pd.DataFrame(place_list, columns = ["장소"]).to_csv("../data/Gangwon_place_list.csv", index=False, encoding = "utf-8-sig")